name: Build Windows App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows --release

      - name: List build output
        run: |
          dir build\windows\runner\Release
          dir build\windows\runner

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: build/windows/runner/Release/